### ISSUE TITLE
Plot Skyplot

### ISSUE THREAD

**Issue by MrBourriz** [Stanford-NavLab/gnss_lib_py#128]
1-plots the satellite skyplot using precise ephemerids sp3, it's possible?
2- How to read sp3 files.

**Comment by betaBison** [comment]
Thanks for your questions. While some SP3 functionality currently exists with a tutorial [here](https://gnss-lib-py.readthedocs.io/en/latest/tutorials/tutorials_parsers_notebook.html#Precise-Ephemerides-Processing), I would suggest waiting for version `0.2.0` to be released which greatly simplifies how to answer your questions.

Both questions will be easy and possible once #127 and #130 are pulled into main and we release gnss_lib_py `v0.2.0`. Once those pull requests are merged in, I'll comment on this issue pointing you towards the relevant SP3 tutorial. Those changes should happen in less than a week.

**Comment by betaBison** [comment]
Please make sure that you've updated to version[ `0.2.0` of gnss-lib-py](https://pypi.org/project/gnss-lib-py/) that we've recently released.

1. The [ephemeris downloader tutorial](https://gnss-lib-py.readthedocs.io/en/latest/tutorials/tutorials_ephemeris_downloader_notebook.html) shows an example of how to download an SP3 file based on a specific date/time and then how to visualize that information using `plot_skyplot`.
2. We added an [SP3 tutorial](https://gnss-lib-py.readthedocs.io/en/latest/tutorials/tutorials_parsers_notebook.html#SP3-File-Parsing) on how to read sp3 files using `glp.Sp3()`.

I'm closing this issue now thanks to the additional functionality we released in version `0.2.0`, but feel free to post any questions/problems you have using the new sp3 functions.
