### ISSUE TITLE
Feature request: Jupyter/Google Colab Install and run support of the repo

### ISSUE THREAD

**Issue by shubhg1996** [Stanford-NavLab/gnss_lib_py#16]
I wanted to quickly process some gnss stuff locally, and I realized that it would be super useful if one could open a jupyter/colab session, run some simple install commands and be able to use gnss_lib_py. Do you think that is doable?

**Comment by ayushmankumar7** [comment]
I think running `!pip install gnss-lib-py` will solve this issue

**Comment by betaBison** [comment]
@ayushmankumar7 is correct.

Since #73 , we are compatible with Python 3.7 (which Google Colab uses). To use `gnsss_lib_py` with Google Colab one needs to:
1. run `!pip install gnss-lib-py`
2. restart the kernel
