### ISSUE TITLE
the tutorials about gnss filter

### ISSUE THREAD

**Issue by ctwillson** [Stanford-NavLab/gnss_lib_py#162]
I have already read the doc in this [link](https://gnss-lib-py.readthedocs.io/en/stable/tutorials/algorithms/tutorials_gnss_filters_notebook.html)
but there is no detailed description about gnss filter,could u fill it?

**Comment by betaBison** [comment]
Yes, we are actively working to update our tutorials in our `tutorial-enhancements` development branch.

Currently there is only a simple demonstration of the EKF, but we hope to add additional information too:
https://github.com/Stanford-NavLab/gnss_lib_py/blob/tutorial-enhancements/notebooks/tutorials/algorithms/gnss_filters.ipynb

If you don't want to wait for the upcoming tutorial, function-level documentation with links to the relevant source code is available here: https://gnss-lib-py.readthedocs.io/en/latest/reference/algorithms/gnss_filters.html

**Comment by betaBison** [comment]
New documentation added with the latest v1.0.3 release.
Tutorial: https://gnss-lib-py.readthedocs.io/en/latest/tutorials/algorithms/tutorials_gnss_filters_notebook.html 

Function-level documentation: https://gnss-lib-py.readthedocs.io/en/latest/reference/algorithms/gnss_filters.html
