### ISSUE TITLE
Add support for Python3.12?

### ISSUE THREAD

**Issue by honglei** [Stanford-NavLab/gnss_lib_py#164]
Python3.12 has been released nearly one year, support for it is reasonnable.

**Comment by betaBison** [comment]
We looked into updating to support Python 3.12 back in April and at the time, we some of our dependencies were not yet compatible with 3.12. I will check again to see if there's updated versions of our dependencies which would allow us to update to Python 3.12. Thanks for the question.

**Comment by betaBison** [comment]
A quick update: I resolved the dependency issues to be able to add support for Python 3.12. Python 3.12 will be supported in version 1.0.3 of gnss-lib-py. We're reviewing the changes in pull request #165

**Comment by betaBison** [comment]
Support for Python 3.12 added with the v1.0.3 release. Please open a new issue if you have any problems with the new release
